# Generated by Django 2.1.5 on 2019-01-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.PositiveIntegerField(default=0, max_length=100),
        ),
    ]
