# Generated by Django 2.1.5 on 2019-01-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site_logo'),
        ),
    ]
