# Generated by Django 2.1.5 on 2019-01-21 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_auto_20190122_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_site', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('google-plus', 'Google +'), ('linkedin', 'Linkedin'), ('website', 'Website')], max_length=10)),
                ('social_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
