# Generated by Django 2.1.5 on 2019-01-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_usersociallinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSocialLinks',
            new_name='UserSocialLink',
        ),
    ]
