# Generated by Django 2.1.5 on 2019-01-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_auto_20190122_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersociallink',
            name='social_site',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('google-plus', 'Google +'), ('linkedin', 'Linkedin'), ('website', 'Website')], default='facebook', max_length=10),
        ),
    ]
