# Generated by Django 2.1.5 on 2019-01-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_auto_20190122_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersociallink',
            old_name='social_link',
            new_name='social_url',
        ),
    ]
